# Generated by Django 4.2.30 on 2026-06-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=10)),
                ('date_jury', models.DateField(blank=True, null=True, verbose_name="Date de l'examen final (jury)")),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Créneau de cours',
                'verbose_name_plural': 'Créneaux de cours',
                'ordering': ['jour_semaine', 'heure_debut', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetailAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(default='Inscrit', max_length=50)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormateurPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_reelle', models.DateField(blank=True, null=True, verbose_name='Date réelle de début')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date réelle de fin')),
                ('heures_effectuees', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Heures effectuées')),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('note_pedagogique', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Note pédagogique (0-5)')),
                ('note_contenu', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Note contenu (0-5)')),
                ('note_organisation', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Note organisation (0-5)')),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séance du Formateur',
                'verbose_name_plural': 'Séances des Formateurs',
                'ordering': ['action__date_debut', 'module__ordre', 'date_debut_reelle', 'formateur__nom'],
            },
        ),
        migrations.CreateModel(
            name='JuryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_formation', models.DecimalField(decimal_places=2, help_text='Cotes obtenues pendant la formation sur 60', max_digits=5, verbose_name='Note formation (/60)')),
                ('note_jury', models.DecimalField(decimal_places=2, help_text='Cotes obtenues pendant le jury sur 40', max_digits=5, verbose_name='Note jury (/40)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note Jury Stagiaire',
                'verbose_name_plural': 'Notes Jury Stagiaires',
            },
        ),
        migrations.CreateModel(
            name='JuryPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jury', models.DateField(verbose_name='Date du jury')),
                ('fichier', models.FileField(upload_to='jury/pv/', verbose_name='PV du jury (PDF)')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PV Jury',
                'verbose_name_plural': 'PVs Jury',
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut_module', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TE', 'Terminé'), ('VA', 'Validé'), ('EF', 'Échec')], default='NC', max_length=2)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Progression du Module',
                'verbose_name_plural': 'Progression des Modules',
                'ordering': ['action__date_debut', 'module__ordre', 'formateur__nom'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nombre_seances', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de séances')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sujet du module',
                'verbose_name_plural': 'Sujets du module',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('planned_start_time', models.TimeField(blank=True, null=True, verbose_name='Heure prévue de début')),
                ('planned_end_time', models.TimeField(blank=True, null=True, verbose_name='Heure prévue de fin')),
                ('planned_topics', models.TextField(blank=True, null=True, verbose_name='Sujets prévus')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date réelle')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Heure réelle de début')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Heure réelle de fin')),
                ('topics_covered', models.TextField(blank=True, null=True, verbose_name='Sujets couverts')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('REALISEE', 'Réalisée'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=10)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes additionnelles')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_animees', to='progress.formateur')),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_progress', to='progress.moduleprogress')),
            ],
            options={
                'verbose_name': 'Progression de la Séance',
                'verbose_name_plural': 'Progression des Séances',
                'ordering': ['planned_date', 'actual_date', 'planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement Bancaire')], default='ESPECES', max_length=20)),
                ('bordereau_photo', models.ImageField(blank=True, null=True, upload_to='paiements/bordereaux/')),
                ('reference', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='progress.action')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='intern.stagiaire')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
