# Generated by Django 4.2.30 on 2026-06-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('progress', '0001_initial'),
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesubject',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='training.module'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_progressions', to='progress.action'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='module_progressions', to='progress.formateur'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.module'),
        ),
        migrations.AddField(
            model_name='jurypv',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jury_pv', to='progress.action'),
        ),
        migrations.AddField(
            model_name='jurynote',
            name='jury_pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='progress.jurypv'),
        ),
        migrations.AddField(
            model_name='jurynote',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_notes', to='intern.stagiaire'),
        ),
        migrations.AddField(
            model_name='formateurperformance',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateur_performances', to='progress.action'),
        ),
    ]
