# Generated by Django 4.2.30 on 2026-06-22 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_initial'),
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurperformance',
            name='evaluateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_formateurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formateurperformance',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='progress.formateur'),
        ),
        migrations.AddField(
            model_name='formateurperformance',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='training.module'),
        ),
        migrations.AddField(
            model_name='detailaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.action'),
        ),
        migrations.AddField(
            model_name='detailaction',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern.stagiaire'),
        ),
        migrations.AddField(
            model_name='actionschedule',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_schedules', to='progress.action'),
        ),
        migrations.AddField(
            model_name='action',
            name='formateurs',
            field=models.ManyToManyField(blank=True, related_name='actions', to='progress.formateur'),
        ),
        migrations.AddField(
            model_name='action',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='training.formation'),
        ),
        migrations.AddField(
            model_name='action',
            name='type_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_liees', to='progress.typeaction'),
        ),
        migrations.AddConstraint(
            model_name='sessionprogress',
            constraint=models.CheckConstraint(check=models.Q(('planned_start_time__lte', models.F('planned_end_time'))), name='session_progress_planned_time_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='sessionprogress',
            constraint=models.CheckConstraint(check=models.Q(('actual_start_time__lte', models.F('actual_end_time'))), name='session_progress_actual_time_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='modulesubject',
            constraint=models.CheckConstraint(check=models.Q(('nombre_seances__gte', 1)), name='module_subject_sessions_minimum'),
        ),
        migrations.AddConstraint(
            model_name='modulesubject',
            constraint=models.UniqueConstraint(fields=('module', 'ordre'), name='module_subject_unique_order'),
        ),
        migrations.AddConstraint(
            model_name='moduleprogress',
            constraint=models.CheckConstraint(check=models.Q(('date_debut_reelle__lte', models.F('date_fin_reelle'))), name='module_progress_date_range_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('formateur', 'action', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='jurynote',
            unique_together={('jury_pv', 'stagiaire')},
        ),
        migrations.AddConstraint(
            model_name='actionschedule',
            constraint=models.CheckConstraint(check=models.Q(('heure_debut__lt', models.F('heure_fin'))), name='action_schedule_time_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='actionschedule',
            constraint=models.UniqueConstraint(fields=('action', 'jour_semaine', 'heure_debut', 'heure_fin'), name='action_schedule_unique_slot'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('date_debut__lte', models.F('date_fin'))), name='action_date_range_valid'),
        ),
    ]
