# Generated by Django 4.2.30 on 2026-09-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='nom_pere',
        ),
    ]
