# Generated by Django 4.2.30 on 2026-09-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_remove_stagiaire_nom_mere_remove_stagiaire_nom_pere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagiaire',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='lieu_naissance',
        ),
    ]
