# Generated by Django 4.2.30 on 2026-09-15 10:22

from django.db import migrations, models


def normaliser_niveau_etude(apps, schema_editor):
    """Aligne les anciennes valeurs 'niveau_etude' sur les nouveaux choix."""
    Stagiaire = apps.get_model("intern", "Stagiaire")
    correspondances = {
        "Diplome d'Etat": "D6",
        "Graduat": "BAC+3",
        "Licence": "BAC+5",
    }
    choix = {"PP4", "D6", "BAC+3", "BAC+5", "Master", "Doctorat"}
    for stagiaire in Stagiaire.objects.all():
        valeur = stagiaire.niveau_etude
        if valeur in choix:
            continue
        stagiaire.niveau_etude = correspondances.get(valeur)
        stagiaire.save(update_fields=["niveau_etude"])


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_remove_stagiaire_date_naissance_and_more'),
    ]

    operations = [
        migrations.RunPython(normaliser_niveau_etude, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stagiaire',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('PP4', 'PP4'), ('D6', 'D6'), ('BAC+3', 'BAC+3'), ('BAC+5', 'BAC+5'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=100, null=True, verbose_name="Niveau d'étude"),
        ),
    ]
