# Generated by Django 4.2 on 2026-05-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('duree', models.IntegerField(default=0)),
                ('duree_heures', models.PositiveIntegerField(default=0, verbose_name='Durée en heures')),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût')),
                ('frais_participation', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais de participation')),
                ('frais_jury', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais du jury')),
                ('frais_materiels', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais matériels')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metiers', to='training.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_heures', models.PositiveIntegerField(default=0, verbose_name='Durée en heures')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateurs', models.ManyToManyField(blank=True, related_name='modules_dispenses', to='progress.formateur')),
                ('metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.metier')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres', to='training.service'),
        ),
    ]
